server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
    url: "jdbc:mysql://112.126.89.93:3306/fxblog?useSSL=false&serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true"
    username: root
    password: root12
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
    cacheNames: boot
    redis:
      timeToLive: 20000
      cache-null-values: false
      keyPrefix: fxblog-
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 20000

