
logging:
  level:
    com.fxtahe.fxblog.mapper:
      debug

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
    url: "jdbc:mysql://localhost:3306/fxblog?useSSL=false&serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

